name: flutter_svga
description: "A Flutter package for rendering SVGA animations with dynamic customization, smooth playback, and high performance."
version: 0.0.6
homepage: https://github.com/5alafawyyy/flutter_svga
repository: https://github.com/5alafawyyy/flutter_svga

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.7
  http: ^1.4.0
  path_drawing: ^1.0.1
  protobuf: ^4.1.0
  audioplayers: ^6.5.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

